export const APP_TITLEBAR_HEIGHT = 40;
export const APP_SIDEBAR_WIDTH = 224;

export const QUICK_PANEL_MIN_LIST_WIDTH = 480;
export const QUICK_PANEL_SPLITTER_WIDTH = 8;
export const QUICK_PANEL_MIN_DETAIL_WIDTH = 360;
export const QUICK_PANEL_MIN_WIDTH =
  QUICK_PANEL_MIN_LIST_WIDTH + QUICK_PANEL_SPLITTER_WIDTH + QUICK_PANEL_MIN_DETAIL_WIDTH;

export const SPELL_LIBRARY_HORIZONTAL_PADDING = 28;
export const SPELL_LIBRARY_MIN_LIST_WIDTH = 480;
export const SPELL_LIBRARY_COLUMN_GAP = 12;
export const SPELL_LIBRARY_MIN_CANDIDATE_WIDTH = 320;
export const SPELL_LIBRARY_MAX_CANDIDATE_WIDTH = 360;
export const SPELL_LIBRARY_MIN_WORKSPACE_WIDTH =
  SPELL_LIBRARY_HORIZONTAL_PADDING +
  SPELL_LIBRARY_MIN_LIST_WIDTH +
  SPELL_LIBRARY_COLUMN_GAP +
  SPELL_LIBRARY_MIN_CANDIDATE_WIDTH;

const MAIN_WINDOW_MIN_WORKSPACE_GUTTER = 8;
const MAIN_WINDOW_MIN_WORKSPACE_WIDTH = Math.max(
  QUICK_PANEL_MIN_WIDTH + MAIN_WINDOW_MIN_WORKSPACE_GUTTER,
  SPELL_LIBRARY_MIN_WORKSPACE_WIDTH
);

export const MAIN_WINDOW_DEFAULT_WIDTH = 1120;
export const MAIN_WINDOW_DEFAULT_HEIGHT = 760;
export const MAIN_WINDOW_MIN_WIDTH = APP_SIDEBAR_WIDTH + MAIN_WINDOW_MIN_WORKSPACE_WIDTH;
export const MAIN_WINDOW_MIN_HEIGHT = 640;
